export const cartActionTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_ITEM: 'ADD_ITEM',
  DELETE_ITEM: 'DELETE_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  REMOVE_ALL_ITEMS: 'REMOVE_ALL_ITEMS'
};
